apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt
  namespace: openai
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chatgpt
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chatgpt
        version: v1
    spec:
      containers:
        - env:
            - name: HIDE_USER_API_KEY
              value: "1"
          envFrom:
            - secretRef:
                name: openai-chatgpt-secrets
          image: registry.ap-southeast-1.aliyuncs.com/neutron/chatgpt
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: chatgpt
          ports:
<<<<<<< HEAD
<<<<<<< HEAD
            - containerPort: 3000
=======
            - containerPort: 8080
>>>>>>> 47474bc (add enum)
=======
            - containerPort: 3000
>>>>>>> 2f1cfe3 (update service)
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   # runAsNonRoot: true
          #   # readOnlyRootFilesystem: true
          #   capabilities:
          #     drop: 
          #       - ALL
          #   seccompProfile:
          #     type: RuntimeDefault
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
